name: Playwright E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright and browsers
        run: npx playwright install --with-deps

      - name: Start Vue app
        run: npm run serve &

      - name: Wait for app to be ready
        uses: jakejarvis/wait-action@v0.1.1
        with:
          url: http://localhost:8080
          timeout: 60

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload test report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
